### ISSUE TITLE
Unvissible car for others

### ISSUE THREAD

**Issue by Eviltjuuh** [bamablood94/qb-dmv#11]
When i take drive test it seems i see the car from outside, but when other people see me driving they only see me floating above road and no car is vissible.

**Comment by TomTheDark** [comment]
Same Problem

**Comment by bamablood94** [comment]
This is a new issue to me. I haven't heard this one before but I think I know what may be causing this

**Comment by TomTheDark** [comment]
> 

I already have this problem

**Comment by bimbolaki** [comment]
how did you fix it, is it onsync or something like that
