### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by gfrast** [bamablood94/qb-dmv#4]
Hi!
i have done everything step by step but when i click on the start button (welcome to the driving school ...) nothing happens. I also don't get an error message in the console.

**Comment by bamablood94** [comment]
Try creating a new character

**Comment by ProMotivated** [comment]
Same issue.. will not let test start.. Have a fixed been found for this error.?

**Comment by DarrianJCairns** [comment]
Same here, anyone found a worksround?

**Comment by bamablood94** [comment]
Try creating a new character. Sorry I just got internet back and i really dont check my github much lol. If you would like me to help a little more, message me on discord Bama94#1994. But Yea try creating a new character and see if that works
