### ISSUE TITLE
multi class license 

### ISSUE THREAD

**Issue by Goykz** [bamablood94/qb-dmv#5]
seems the if i do the regular driving test i cant take  CDL test

**Comment by bamablood94** [comment]
Cdl test isn't fully working atm

**Comment by ChickenDipper1** [comment]
The CDL test is still an option in the UI, may be best to remove. I have done so :)
Quick fix:
Comment out the follow lines in client.lua:


      {
        header = "Start CDL Drving Test",
        txt = "$"..Config.Amount['cdl'].."",
        params = {
          event = 'qb-dmv:startcdl'
        }
      }
